---
- name: "Install git,python3"
  ansible.builtin.package:
    name: "{{ item.name }}{{ item.version }}"
    update_cache: yes
    state: present
  with_items:
    - "{{ packages_git_py }}"
