---
- name: "Install git and pyhton3"
  import_tasks: git-python.yml
  become: true

- name: "Install Docker"
  import_tasks: docker.yml
  become: true

- name: "Add sudo to user"
  set_fact: sudo=",{{ sudo_groups }}"
  when: sudo_groups is defined

- name: "Create user hw20"
  ansible.builtin.user:
    name: "{{ item.name }}"
    shell: "{{ item.shell }}"
    home: "{{ item.home }}"
    state: present
  with_items:
    - "{{ hw20_user }}"

- name: "Clone public git repo"
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    clone: yes
  with_items:
    - "{{ git }}"
