---
- name: "Install git,docker,python3"
  ansible.builtin.package:
    name: "{{ item.name }}"
    update_cache: yes
  with_items:
    - "{{ packages_git_py_docker }}"

- name: "Create user hw20"
  ansible.builtin.user:
    name: "{{ item.name }}"
    shell: "{{ item.shell }}"
    home: "{{ item.home }}"
    state: present
  with_items:
    - "{{ hw20_user }}"

- name: "Clone public git repo"
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    clone: yes
  with_items:
    - "{{ git }}"
