---
- block: #Block for Ubuntu
    - name: Install git,docker,python3
      apt: name={{ item }}  state=latest update_cache=yes
      loop:
        - git
        - docker.io
        - python3

  when: ansible_os_family == "Debian"

        
- block: #Install for Centos
    - name: Install git,docker,python3
      yum: name={{ item }} state=latest update_cache=yes
      loop:
        - git
        - docker
        - python3

  when: ansible_os_family == "RedHat"

- name: Create user hw20 with /bin/sh and home folder /opt/hw20
  user:
    name: hw20
    shell: "{{ SH }}"
    home: "{{ HF }}"
