---
SSH_PORT: 22
git:
  repo: 'https://github.com/nsdementar/HW9.git'
  dest: "/opt/hw20/git/"
hw20_user: 
  - { name: hw20, shell: /bin/bash, home: /opt/hw20/ }
curl_files_deb:
  - { src: "curl.deb", dest: "/opt/hw20/curl.deb", owner: "hw20", mode: "0744" }
curl_files_rpm:
  - { src: "curl.rpm", dest: "/opt/hw20/curl.rpm", owner: "hw20", mode: "0744" }
