---
SSH_PORT: 22
git:
  repo: 'https://github.com/nsdementar/HW9.git'
  dest: "/opt/hw20/git/"
hw20_user: 
  - { name: hw20, shell: /bin/bash, home: /opt/hw20/ }
template_var:
 - { src: "main.j2", dest: "/opt/hw20/HW20_FILE_INFO", owner: "hw20", mode: "0644" }
deamon_templates:
 - { src: "hw21.sh", dest: "/opt/hw20/logdeamon.sh", owner: "root", mode: "0744" }
 - { src: "hw21.service.j2", dest: "/lib/systemd/system/logsysd.service", owner: "root", mode: "0644" }
 - { src: "hw21.timer.j2", dest: "/lib/systemd/system/logsysd.timer", owner: "root", mode: "0644" }
deamon_var:
  OnUnitActiveSec: 30s
  OnBootSec: 10s
  ExecStart: /opt/hw20/hw21.sh
