---
SSH_PORT: 22
git:
  repo: 'https://github.com/nsdementar/HW9.git'
  dest: "/opt/hw20/git/"
hw20_user: 
  - { name: hw20, shell: /bin/bash, home: /opt/hw20/ }
template_var:
 - { src: "main.j2", dest: "/opt/hw20/HW20_FILE_INFO", owner: "hw20", mode: "0644" }
