---
SSH_PORT: 22
file:
  - { content: "", dest: "/opt/hw23_test_file", owner: "root", group: "root", mode: "0644" }
s_link:
  - { src: "/etc/hosts", dest: "/opt/hw23_link", owner: "root", group: "root", mode: "0644" }
docker: docker
nginx: nginx
