all:
   hosts:
   children:
      Group1:
         hosts:
           node1:
                   ansible_host: 10.10.18.228
      Group2:
         hosts:
           node2:
                   ansible_host: 10.10.18.229
      Group3:
         children:
           Group1:
           Group2:
