all:
  hosts:
    children:
      Group1:
        hosts:
          node1:
            10.10.18.228
      Group2:
         hosts:
           node2:
            10.10.18.229
      Group3:
        children:
          Group1
          Group2
