name: HW29

on:
  push:
    branches:
    - HW29

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
    - name: Lint Ansible Playbook
      uses: ansible/ansible-lint-action@master
      with:
        targets: "HW20/HW20.yml"

    - name: Run playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: HW29/HW29.yml
        #directory: HW20
        inventory: localhost
